apiVersion: v1
kind: Pod
metadata:
  name: fencing-operator
spec:
  containers:
  - name: operator
    image: quay.io/beekhof/fencing-operator:latest
    # Defaults to just '/usr/local/bin/rss-operator' this is how we'd enable
    # debug logging:
    # command: [ "/usr/local/bin/rss-operator", "-alsologtostderr", "-v", "1" ]
    env:
    - name: POD_NAMESPACE
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.namespace
    - name: POD_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    - name: POD_IMAGE
      value: quay.io/beekhof/fencing-operator:latest
