apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: fencing-operator
  name: single-host-non-destructive
data:
  fencing-config: |
    nodeSelector:
    - spec.Name: somehost
    methods:
    - set:
      name: openstack-isolate
      mechanisms:
      - driver: openstack
        module: network
        config:
        - user: admin
        - password: admin
        - auth_url: https://1.1.1.1:5000
      - driver: openstack
        module: disk
        config:
        - user: admin
        - password: admin
        - auth_url: https://1.1.1.1:5000
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: fencing-operator
  name: default-openstack-with-baremetal-backup
data:
  fencing-config: |
    methods:
    - set:
      name: openstack-power
      mechanisms:
      - driver: openstack
        config:
        - user: admin
        - auth_url: https://1.1.1.1:5000
        secrets:
        - password: overcloud-secret
    - set:
      name: fallback
      mechanisms:
      - driver: baremetal
        module: ipmilan
        dynamic_config:
        - field: ip
          map:
          - somehost: 1.2.3.4
          - otherhost: 1.2.3.5
        config:
        - user: admin
        secrets:
        - password: ipmi-secret
